export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_ADD_ITEM = "ORDER_ADD_ITEM";
export const ORDER_ADD_NEW_ITEM = "ORDER_ADD_NEW_ITEM";
export const ORDER_REMOVE_ITEM = "ORDER_REMOVE_ITEM";
export const ORDER_DELETE_ITEM = "ORDER_DELETE_ITEM";
