export const TABLES_LIST_REQUEST = "TABLES_LIST_REQUEST";
export const TABLES_LIST_SUCCESS = "TABLES_LIST_SUCCESS";
export const TABLES_LIST_FAIL = "TABLES_LIST_FAIL";

export const ROOMS_LIST_REQUEST = "ROOMS_LIST_REQUEST";
export const ROOMS_LIST_SUCCESS = "ROOMS_LIST_SUCCESS";
export const ROOMS_LIST_FAIL = "ROOMS_LIST_FAIL";
